name: hello-world

on: 
 push:
 schedule:
  - cron: "*/5 * * * *"

jobs:
  running-the-code: 

    runs-on: ubuntu-latest

    steps:
      - name: repository code
        uses: actions/checkout@v4
      - run: echo "$(cat hello_world.txt)"
    
